POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "nyt oikeesti illan viimeinen",
  "author": "väsyttää",
  "url": "https://wwaki-hintsa-voittamisen-anatomia?variant=21150604886105&gad_source=1&gclid=CjwKCAjw2dG1BhB4EiwA998cqHLLXVprkYJ5Q_4NKEq9WZnBJ6BVvbt5BONPbtGjZOORqkBhpTEIQBoCelQQAvD_BwE",
  "likes": 22
}